server:
  port: 6868
eureka:
  client:
    #不将自己（当前服务）注册到Eureka服务中
    register-with-eureka: false
    #不从Eureka中提取注册信息
    fetch-registry: false
    service-url:
      #Eureka客户端与服务端通信的地址（服务注册中心地址）
      defaultZone: http://localhost:6868/eureka