server:
  port: 12000
spring:
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/jackyzcz/tensquare-spring-cloud-config.git
  rabbitmq:
    host: 192.168.25.130
#暴露触发消息总线的地址
management:
  endpoints:
    web:
      exposure:
        include: bus-refresh